{% set version = "2.1" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: 6dc52924dc0bc710a5d16794e6b3480b2c7c08b07729505feab2b2c16661ff6e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - jschueller
