{% set version = "1.9.4" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: 605f89ad5fdbfefe30cdc293303665eff2d188865d4dbe4eb510bba1edfbfce3

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - backports.functools_lru_cache  # [py<33]

test:
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup 

extra:
  recipe-maintainers:
    - jschueller
