{% set version = "2.8" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: e2dd4a40a628cb5f28f6d4b0db8800b8f581b65bb380b97de22ba5ca8d72572f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - beautifulsoup4
    - python {{ python_min }}
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - MementoRC
    - jschueller
