{% set version = "2.8.1" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: 4cf733bc50fa805f5df4b8ef4740fc0e0fa6218cf3006269afd3f9d6d80fd350

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - beautifulsoup4
    - python {{ python_min }}
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - MementoRC
    - jschueller
