{% set version = "2.3" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: e4860f889dfa88774c07da0b276b70c073b6470fa1a4a8350800bb7bce3dcc76

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  requires:
    - beautifulsoup4
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - jschueller
