{% set version = "2.9.1" %}

package:
  name: soupsieve
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: c33e6605bbc71dd628b00c632d58ae607c22bade247e52553928f83bbb75b4ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  requires:
    - beautifulsoup4
    - python {{ python_min }}
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - MementoRC
    - jschueller
